### ISSUE TITLE
Non-expanding VS

### ISSUE THREAD

**Issue by jpwiedekopf** [MLambarki/dktk-on-fhir#6]
Two VS don't expand (well, they do, but the expansion is empty) using Ontoserver, due to the Regex format. The two affected VS are `MorphologieICDO3VS` and `TopographieICDO3VS` with these regexes in `ValueSet.compose.include` for Topo:

```json
{
  "system": "urn:oid:2.16.840.1.113883.6.43.1",
  "filter": [
    {
      "property": "code",
      "op": "regex",
      "value": "C\\d\\d\\.\\d(\\d)?"
    }
  ]
}
```

and `\\d\\d\\d\\d/\\d` for Morpho.

I recommend changing the regex for Morphologie to the equivalent `[0-9]{4}/[0-9]`, and Topographie to the not-strictly-equivalent `C.*` (all topo codes in the ICD-O start with a C, so the intended expansion is equivalent).

**Comment by MLambarki** [comment]
Thank you very much for your suggestion!
I hope I have understood the suggestion correctly.
- **Topo:**  \d\d\d\d/\d or \d{4}/\d or [0-9]{4}/[0-9] are basically identical
- **Morpho:** The expression `C.*` would be too broad, as it would include everything after a “C”.

(PS: sorry for the late response due to vacation).
